// <auto-generated />
namespace Logs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class vasiliystan_ba0bf0ee564844538f34c4596c09d15b : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vasiliystan_ba0bf0ee564844538f34c4596c09d15b));
        
        string IMigrationMetadata.Id
        {
            get { return "201912220139288_vasiliy.stan_ba0bf0ee564844538f34c4596c09d15b"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
